### ISSUE TITLE
"Error: spawn ENOENT" – ruby-sass-loader not working at all on Windows 7 x64

### ISSUE THREAD

**Issue by martyfmelb** [ddelbondio/ruby-sass-loader#1]
child_process.execFile fails to execute Sass at all on Windows, giving me "Error: spawn ENOENT".

Changing execFile('sass', ...) to execFile('sass.bat', ...) gets me part way there.

However, I still get path problems like this:
"WARNING in ./~/css-loader!./~/ruby-sass-loader?outputStyle=expanded!./src/styles/main.scss: Error: Cannot resolve 'file' or 'directory' ../../../../work/creative/2015/frontend/2015-03-11_react-webpack-workflow/src/styles/Gamebar.scss"

I'm running ruby 1.9.3p545 and SASS latest (3.4.13).

**Comment by ddelbondio** [comment]
I won't be able to look into the windows issue before next week.
The path issue looks interesting. From which folder are you triggering webpack? Looking at the path, webpack steps up 4 (../../../../) directories, but then tries to step down 5 (work/creative/2015/frontend/2015-03-11_react-webpack-workflow/) which looks somewhat wrong to me
