### ISSUE TITLE
"Cannot find source file" warning

### ISSUE THREAD

**Issue by atgillette** [ddelbondio/ruby-sass-loader#7]
Hi,

I'm trying to use the loader to generate a sourcemap for my scss files.  Here's my loader declaration:

``` javascript
{
     test: /\.scss$/,
     loader: 'style!css?sourceMap!ruby-sass?buildPath=./.tmp'
},
```

I'm getting the following warning:

> WARNING in ./~/css-loader?sourceMap!./~/ruby-sass-loader?buildPath=./.tmp&includePaths[]=/Users/user/Documents/application!./src/js/main.scss
> Cannot find source file 'src/js/main.scss': Error: Cannot resolve 'file' or 'directory' ./src/js/main.scss in ./.tmp

Any suggestions on how this can be fixed?

Thanks,

Adrian

**Comment by ddelbondio** [comment]
I have reworked that part of the code, so this should be fixed in 0.3.0 now.
