### ISSUE TITLE
How add line_comments = true and images_dir to resolve images?

### ISSUE THREAD

**Issue by arthurkhlghatyan** [ddelbondio/ruby-sass-loader#9]
It seems I can't add line_comments option and resolve images. Maybe I can include config.rb file?

Any ideas?

**Comment by rickysullivan** [comment]
`child_process.execFile(sass, args, {cwd: query.configPath}, function(err, stdout, stderr) { ... }`

`'ruby-sass?compass=true&configPath=' + path.resolve(__dirname, '..')`

Saved my bacon.

**Comment by rickysullivan** [comment]
Or `{cwd: (query.configPath || this.context) }`

**Comment by ddelbondio** [comment]
This has been added as `cwd` setting. Just point this to your compass base folder and it should work automatically.
